import type { PracticeMode, SpeechLanguage } from "@/types";

/**
 * Mode-specific audience questions used by the heuristic provider
 * ({topic} is replaced with the session's topic). The OpenAI provider
 * generates its own tailored questions from the transcript instead.
 */
export const AUDIENCE_QUESTIONS: Record<
  SpeechLanguage,
  Record<PracticeMode, string[]>
> = {
  fr: {
    presentation: [
      "Quelle est l'idée principale que vous voulez que nous retenions sur {topic} ?",
      "Quelles sources appuient ce que vous avez présenté ?",
      "Comment {topic} affecte-t-il votre public au quotidien ?",
      "Quelle partie de votre présentation est la plus discutable, et pourquoi ?",
      "Si vous n'aviez que 30 secondes, comment résumeriez-vous votre message ?",
      "Qu'avez-vous appris en préparant cette présentation ?",
      "Quelles questions attendiez-vous de notre part ?",
    ],
    "startup-pitch": [
      "Quelle est la taille réelle de votre marché et comment l'avez-vous calculée ?",
      "Qu'est-ce qui vous différencie de la concurrence existante sur {topic} ?",
      "Quel est votre modèle de revenus et votre coût d'acquisition client ?",
      "Quelle traction avez-vous aujourd'hui : utilisateurs, revenus, accords ?",
      "Pourquoi votre équipe est-elle la bonne pour exécuter ce projet ?",
      "Combien levez-vous et à quoi cela servira-t-il ?",
      "Quel est le plus grand risque, et comment le limitez-vous ?",
      "Que se passe-t-il si un acteur établi copie votre idée ?",
    ],
    interview: [
      "Pourquoi voulez-vous exactement ce poste ?",
      "Parlez-moi d'un problème difficile que vous avez résolu, et comment.",
      "Quel est votre plus grand point faible, et que faites-vous pour l'améliorer ?",
      "Où vous voyez-vous dans cinq ans ?",
      "Décrivez un conflit d'équipe et comment vous l'avez géré.",
      "Qu'est-ce qui vous distingue des autres candidats ?",
      "Quelles questions avez-vous pour nous ?",
    ],
    "oral-exam": [
      "Définissez les concepts clés de {topic} avec vos propres mots.",
      "Quels auteurs ou théories fondent votre exposé ?",
      "Donnez un exemple concret illustrant ce que vous avez expliqué.",
      "Quelles sont les limites de l'approche que vous avez présentée ?",
      "Comment {topic} se rattache-t-il au reste du programme ?",
      "Si vous refaisiez cet exposé, que changeriez-vous ?",
      "Expliquez, étape par étape, la partie que vous jugez la plus complexe.",
    ],
    "project-defense": [
      "Quel problème concret votre projet résout-il, et pour qui ?",
      "Justifiez les choix méthodologiques que vous avez faits sur {topic}.",
      "Quelles alternatives avez-vous écartées, et pourquoi ?",
      "Quelles sont les principales limites de vos résultats ?",
      "Comment avez-vous validé que votre solution fonctionne ?",
      "Que feriez-vous différemment si vous recommenciez ?",
      "Quelles perspectives futures propose votre projet ?",
      "Quelle contribution originale apporte votre travail par rapport à l'existant ?",
    ],
    "brevet-oral": [
      "Pourquoi as-tu choisi ce sujet pour {topic} ?",
      "Quelles difficultés as-tu rencontrées pendant ce projet ?",
      "Qu'est-ce que ce projet t'a appris sur toi-même ?",
      "Comment as-tu organisé ton travail dans le temps imparti ?",
      "As-tu travaillé seul(e) ou en groupe ? Comment cela s'est-il passé ?",
      "Quel lien fais-tu entre {topic} et ton projet d'orientation ?",
      "Si tu devais recommencer, que changerais-tu ?",
    ],
    "bac-francais-oral": [
      "Quel est le mouvement littéraire auquel appartient ce texte sur {topic} ?",
      "Quels procédés stylistiques avez-vous relevés dans ce passage ?",
      "En quoi ce texte est-il représentatif de l'œuvre dans son ensemble ?",
      "Quelle est la visée de l'auteur dans cet extrait ?",
      "Pouvez-vous relier ce texte à un autre étudié cette année ?",
      "Quelle œuvre de votre liste avez-vous préférée, et pourquoi ?",
      "Quel est l'intérêt littéraire de ce texte selon vous ?",
    ],
    "grand-oral": [
      "Pourquoi avez-vous choisi cette question sur {topic} ?",
      "Quel lien faites-vous entre cette question et vos spécialités ?",
      "Quelles sources avez-vous utilisées pour construire votre argumentation ?",
      "Quelle est la limite de votre raisonnement ?",
      "Comment cette question s'inscrit-elle dans votre projet d'orientation ?",
      "Si vous deviez approfondir un aspect, lequel choisiriez-vous ?",
      "Quel regard critique portez-vous sur votre propre travail ?",
    ],
  },
  es: {
    presentation: [
      "¿Cuál es la idea principal que quieres que recordemos sobre {topic}?",
      "¿Qué fuentes respaldan lo que has contado?",
      "¿Cómo afecta {topic} a tu audiencia en el día a día?",
      "¿Qué parte de tu presentación consideras más discutible y por qué?",
      "Si tuvieras solo 30 segundos, ¿cómo resumirías tu mensaje?",
      "¿Qué aprendiste al preparar esta presentación?",
      "¿Qué preguntas esperabas que te hiciéramos?",
    ],
    "startup-pitch": [
      "¿Cuál es el tamaño real de tu mercado y cómo lo has calculado?",
      "¿Qué te diferencia de la competencia que ya existe en {topic}?",
      "¿Cuál es tu modelo de ingresos y tu coste de adquisición de clientes?",
      "¿Qué tracción tenéis hasta hoy: usuarios, ingresos, acuerdos?",
      "¿Por qué tu equipo es el adecuado para ejecutar esto?",
      "¿Cuánto capital buscáis y en qué lo vais a gastar?",
      "¿Cuál es el mayor riesgo del proyecto y cómo lo mitigáis?",
      "¿Qué pasa si un gigante del sector copia vuestra idea?",
    ],
    interview: [
      "¿Por qué quieres trabajar exactamente en este puesto?",
      "Cuéntame un problema difícil que resolviste y cómo lo hiciste.",
      "¿Cuál consideras tu mayor debilidad y qué haces al respecto?",
      "¿Dónde te ves dentro de cinco años?",
      "Describe una situación de conflicto en equipo y cómo la gestionaste.",
      "¿Qué te diferencia del resto de candidaturas?",
      "¿Qué preguntas tienes tú para nosotros?",
    ],
    "oral-exam": [
      "Define los conceptos clave de {topic} con tus propias palabras.",
      "¿Qué autores o teorías fundamentan tu exposición?",
      "Pon un ejemplo práctico que ilustre lo que has explicado.",
      "¿Qué limitaciones tiene el enfoque que has presentado?",
      "¿Cómo se relaciona {topic} con el resto del temario?",
      "Si repitieras la exposición, ¿qué cambiarías?",
      "Explica la parte que consideres más compleja, paso a paso.",
    ],
    "project-defense": [
      "¿Qué problema concreto resuelve tu proyecto y para quién?",
      "Justifica las decisiones metodológicas que tomaste en {topic}.",
      "¿Qué alternativas descartaste y por qué?",
      "¿Cuáles son las principales limitaciones de tus resultados?",
      "¿Cómo validaste que tu solución funciona?",
      "¿Qué harías diferente si empezaras de nuevo?",
      "¿Qué líneas futuras de trabajo propone tu proyecto?",
      "¿Qué aportación original hace tu trabajo frente a lo existente?",
    ],
    "brevet-oral": [
      "¿Por qué elegiste este tema para {topic}?",
      "¿Qué dificultades encontraste durante el proyecto?",
      "¿Qué te ha enseñado este proyecto sobre ti mismo?",
      "¿Cómo organizaste tu trabajo en el tiempo disponible?",
      "¿Trabajaste solo o en grupo? ¿Cómo fue la experiencia?",
      "¿Qué relación ves entre {topic} y tu proyecto de orientación?",
      "Si tuvieras que empezar de nuevo, ¿qué cambiarías?",
    ],
    "bac-francais-oral": [
      "¿A qué movimiento literario pertenece este texto sobre {topic}?",
      "¿Qué recursos estilísticos has identificado en este pasaje?",
      "¿En qué sentido este texto representa el conjunto de la obra?",
      "¿Cuál es la intención del autor en este fragmento?",
      "¿Puedes relacionar este texto con otro estudiado este curso?",
      "¿Qué obra de tu lista has preferido, y por qué?",
      "¿Cuál es, en tu opinión, el interés literario de este texto?",
    ],
    "grand-oral": [
      "¿Por qué elegiste esta pregunta sobre {topic}?",
      "¿Qué relación estableces entre esta pregunta y tus especialidades?",
      "¿Qué fuentes has utilizado para construir tu argumentación?",
      "¿Cuál es el límite de tu razonamiento?",
      "¿Cómo encaja esta pregunta en tu proyecto de orientación?",
      "Si tuvieras que profundizar en un aspecto, ¿cuál elegirías?",
      "¿Qué mirada crítica tienes sobre tu propio trabajo?",
    ],
  },
  en: {
    presentation: [
      "What is the one idea you want us to remember about {topic}?",
      "What sources back up what you presented?",
      "How does {topic} affect your audience day to day?",
      "Which part of your talk is most debatable, and why?",
      "If you had only 30 seconds, how would you summarize your message?",
      "What did you learn while preparing this presentation?",
      "What questions were you expecting from us?",
    ],
    "startup-pitch": [
      "What is your real market size and how did you calculate it?",
      "What differentiates you from existing competitors in {topic}?",
      "What is your revenue model and customer acquisition cost?",
      "What traction do you have today — users, revenue, deals?",
      "Why is your team the right one to execute this?",
      "How much are you raising and what will you spend it on?",
      "What is the biggest risk, and how do you mitigate it?",
      "What happens if an incumbent copies your idea?",
    ],
    interview: [
      "Why do you want this specific role?",
      "Tell me about a hard problem you solved and how.",
      "What is your biggest weakness and what are you doing about it?",
      "Where do you see yourself in five years?",
      "Describe a team conflict and how you handled it.",
      "What sets you apart from other candidates?",
      "What questions do you have for us?",
    ],
    "oral-exam": [
      "Define the key concepts of {topic} in your own words.",
      "Which authors or theories underpin your presentation?",
      "Give a practical example that illustrates what you explained.",
      "What are the limitations of the approach you presented?",
      "How does {topic} relate to the rest of the syllabus?",
      "If you repeated the presentation, what would you change?",
      "Walk me through the most complex part, step by step.",
    ],
    "project-defense": [
      "What concrete problem does your project solve, and for whom?",
      "Justify the methodological choices you made in {topic}.",
      "Which alternatives did you discard, and why?",
      "What are the main limitations of your results?",
      "How did you validate that your solution works?",
      "What would you do differently if you started over?",
      "What future work does your project propose?",
      "What original contribution does your work make?",
    ],
    "brevet-oral": [
      "Why did you choose this topic for {topic}?",
      "What difficulties did you run into during the project?",
      "What did this project teach you about yourself?",
      "How did you organize your work within the time available?",
      "Did you work alone or in a group? How did that go?",
      "What link do you see between {topic} and your career orientation?",
      "If you had to start over, what would you change?",
    ],
    "bac-francais-oral": [
      "Which literary movement does this text on {topic} belong to?",
      "What stylistic devices did you identify in this passage?",
      "How is this text representative of the work as a whole?",
      "What is the author's intent in this excerpt?",
      "Can you connect this text to another one studied this year?",
      "Which work from your reading list did you prefer, and why?",
      "What's the literary interest of this text, in your view?",
    ],
    "grand-oral": [
      "Why did you choose this question on {topic}?",
      "What link do you draw between this question and your specialties?",
      "What sources did you use to build your argument?",
      "What is the limit of your reasoning?",
      "How does this question fit into your career orientation project?",
      "If you had to go deeper into one aspect, which would you pick?",
      "What critical view do you have of your own work?",
    ],
  },
};
